### ISSUE TITLE
Load Interstitial Ad

### ISSUE THREAD

**Issue by adrianha** [melihmucuk/react-native-admob-sample#1]
Hello,
I am just using your library to attach admob in my react-native application.
I ran your example and was trying to show second interstitial ads but i got no response (ads didnt pop up). Can you help me to show the ads everytime i press the button because for now the ads just show only once when first pressed..

**Comment by melihmucuk** [comment]
I explained this in notes section. You have to call `loadInterstitial` function every time before showing interstitial ads. @adrianha

**Comment by adrianha** [comment]
Oh okay.. I thought call loadInterstitial function in constructor is enough.. Thank you for the information.
