### ISSUE TITLE
can you create instruction how to integrate to an existing IOS app?

### ISSUE THREAD

**Issue by shrimpywu** [melihmucuk/react-native-admob-sample#3]

**Comment by hasen6** [comment]
Yes any tips on how to actually use this would be great. I've created a few apps with React Native and with my current app I want to use admob. I couldn't get your sample to work with React Native 0.17. I think your xcodeproj file is in the wrong place but I don't know how to fix that.

**Comment by melihmucuk** [comment]
I added more detail to readme.

**Comment by hasen6** [comment]
Now I'm even more confused. Why do we follow the admob tutorial for objective C?? I thought this was for use with react native.

**Comment by hasen6** [comment]
Now I'm even more confused. Why do we follow the admob tutorial for objective C?? I thought this was for use with react native.

**Comment by melihmucuk** [comment]
this is wrapper for admob ios sdk (objective-c),  you should add admob ios sdk to your project, and copy wrappers (AdMobManager.h and .m) then use it.
