### ISSUE TITLE
Hi, I got an error while I was showing Interstitial, Could you please suggest me?

### ISSUE THREAD

**Issue by niponph** [melihmucuk/react-native-admob-sample#4]
2015-12-29 08:21:01.268 myapp[[71416:1306481] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GADInterstitialViewController navItem]: unrecognized selector sent to instance 0x7fe48a0535a0'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0000000109f82e65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000108e7fdeb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000109f8b48d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x0000000109ed890a ___forwarding_** + 970
    4   CoreFoundation                      0x0000000109ed84b8 _CF_forwarding_prep_0 + 120
    5   MeeMovie                            0x00000001084e5fdf __69-[RCTNavigator navigationController:willShowViewController:animated:]_block_invoke + 191
    6   UIKit                               0x000000010ca2177d -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 300
    7   UIKit                               0x000000010ca1e1ff -[_UIViewControllerTransitionContext __runAlongsideAnimations] + 187
    8   UIKit                               0x000000010c0a0bd3 -[UIViewAnimationState _runAlongsideAnimations] + 29
    9   UIKit                               0x000000010c09f897 -[UIViewAnimationState pop] + 33
    10  UIKit                               0x000000010c09e0bd +[UIViewAnimationState popAnimationState] + 65
    11  UIKit                               0x000000010c48f531 -[UINavigationTransitionView transition:fromView:toView:] + 2640
    12  UIKit                               0x000000010c1f3cf5 -[UINavigationController _startTransition:fromViewController:toViewController:] + 3291
    13  UIKit                               0x000000010c1f42f1 -[UINavigationController _startDeferredTransitionIfNeeded:] + 890
    14  UIKit                               0x000000010c1f53af -[UINavigationController __viewWillLayoutSubviews] + 57
    15  UIKit                               0x000000010c39bff7 -[UILayoutContainerView layoutSubviews] + 248
    16  UIKit                               0x000000010c0ce4a3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    17  QuartzCore                          0x000000010bd6059a -[CALayer layoutSublayers] + 146
    18  QuartzCore                          0x000000010bd54e70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    19  UIKit                               0x000000010c0bdd0d -[UIView(Hierarchy) layoutBelowIfNeeded] + 1129
    20  UIKit                               0x000000010c2061a8 -[UITabBarController _layoutViewController:] + 877
    21  UIKit                               0x000000010c2107dc -[UITabBarController _updateLayoutForStatusBarAndInterfaceOrientation] + 164
    22  UIKit                               0x000000010c1b5edf -[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:] + 1242
    23  UIKit                               0x000000010c0c80ed -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1613
    24  UIKit                               0x000000010c0c7dfe -[UIView(Internal) _didMoveFromWindow:toWindow:] + 862
    25  UIKit                               0x000000010c0c7dfe -[UIView(Internal) _didMoveFromWindow:toWindow:] + 862
    26  UIKit                               0x000000010c0c7dfe -[UIView(Internal) _didMoveFromWindow:toWindow:] + 862
    27  UIKit                               0x000000010c0c7dfe -[UIView(Internal) _didMoveFromWindow:toWindow:] + 862
    28  UIKit                               0x000000010c0c7dfe -[UIView(Internal) _didMoveFromWindow:toWindow:] + 862
    29  UIKit                               0x000000010c0bd06a __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 155
    30  Foundation                          0x0000000108a55c9a -[NSISEngine withBehaviors:performModifications:] + 155
    31  UIKit                               0x000000010c0bcf88 -[UIView(Hierarchy) _postMovedFromSuperview:] + 575
    32  UIKit                               0x000000010c0cad8f -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1967
    33  UIKit                               0x000000010c17c21f -[UITransitionView transition:fromView:toView:removeFromView:] + 1865
    34  UIKit                               0x000000010ca41998 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 3645
    35  UIKit                               0x000000010c181e27 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 2638
    36  UIKit                               0x000000010c0234a2 _runAfterCACommitDeferredBlocks + 317
    37  UIKit                               0x000000010c036c01 _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
    38  UIKit                               0x000000010c042af3 _afterCACommitHandler + 90
    39  CoreFoundation                      0x0000000109eae367 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    40  CoreFoundation                      0x0000000109eae2d7 __CFRunLoopDoObservers + 391
    41  CoreFoundation                      0x0000000109ea3f2b __CFRunLoopRun + 1147
    42  CoreFoundation                      0x0000000109ea3828 CFRunLoopRunSpecific + 488
    43  GraphicsServices                    0x000000010ed85ad2 GSEventRunModal + 161
    44  UIKit                               0x000000010c017610 UIApplicationMain + 171
    45  MeeMovie                            0x000000010844b09f main + 111
    46  libdyld.dylib                       0x000000010dcd192d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by niponph** [comment]
The error happen when close the interstitial. @melihmucuk

**Comment by melihmucuk** [comment]
what is your react native and admob sdk versions ?

**Comment by niponph** [comment]
React-native version is 0.15.0 and google admob ios sdk: 7.4.1

**Comment by melihmucuk** [comment]
did you add admob sdk and other related frameworks to your xcode project ? described [here](https://developers.google.com/admob/ios/quick-start)

**Comment by niponph** [comment]
yup I did add admob sdk. the ads can show successfully but when i try to close the ads, it crash and show the error above.

**Comment by niponph** [comment]
ohhh sorry, I need to add other framework right. this one. I didn't add it. :( may be cause . .... Thanks

AdSupport
AudioToolbox
AVFoundation
CoreGraphics
CoreMedia
CoreTelephony
EventKit
EventKitUI
MessageUI
StoreKit
SystemConfiguration

let me test. thanks for fast response :+1:

**Comment by melihmucuk** [comment]
Yes, you have to add required frameworks too. Let me know if it works.

**Comment by niponph** [comment]
Hi, I already add framework but it still not working. Did i miss something?

**Comment by melihmucuk** [comment]
describe "not working". what is the error message ? @niponph

**Comment by melihmucuk** [comment]
I closed this now, please do not hesitate to reopen it.
