### ISSUE TITLE
XCode wont compile the example

### ISSUE THREAD

**Issue by naji247** [melihmucuk/react-native-admob-sample#5]
I cloned, ran npm i, and opened the xcode project. Unfortunately it wont build with errors like this.

Am I doing something wrong? My other xcode projects open.

<img width="585" alt="screen shot 2016-03-20 at 1 23 29 pm" src="https://cloud.githubusercontent.com/assets/1920483/13906895/facedf00-ee9e-11e5-9903-dbd2f1d294ad.png">

<img width="1111" alt="screen shot 2016-03-20 at 1 19 42 pm" src="https://cloud.githubusercontent.com/assets/1920483/13906873/9d293d6e-ee9e-11e5-89eb-7459303877d5.png">

**Comment by melihmucuk** [comment]
Did you follow [this tutorial](https://developers.google.com/admob/ios/quick-start) and add required libs ?
